#**Wstęp do TensorFlow**

In [1]:
%pylab inline
import tensorflow as tf
import numpy as np

Populating the interactive namespace from numpy and matplotlib


Załadowanie danych

In [3]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import label_binarize, scale

data = load_wine()
data

data_X = scale(data['data'].astype(float32))
data_y_lab = data['target']
data_y = label_binarize(data['target'], classes = [0,1,2])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:236: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  "Numerical issues were encountered "
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:255: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  "Numerical issues were encountered "


Klasyfikacja wieloklasowa

In [4]:
alpha = 0.01
X = tf.constant(data_X)
W = tf.Variable(np.random.random((10,3)).astype(float32))
b = tf.Variable(1.0)
H = tf.Variable(np.random.random((data_X.shape[1],10)).astype(float32))
hb = tf.Variable(1.0)
y_true = tf.constant(data_y)


for epoch in range(100):
  with tf.GradientTape() as g:
    hidact = tf.sigmoid(tf.matmul(X,H) + hb)
    logits = tf.matmul(hidact,W) + b
    y_pred = tf.argmax(tf.nn.softmax(logits),axis=1)
    accuracy = sum(y_pred == data_y_lab) / data_y_lab.size
    loss = tf.reduce_sum(tf.nn.softmax_cross_entropy_with_logits(y_true, logits))

    d = g.gradient(loss,[H,hb,W,b])
    H.assign_sub(d[0]*alpha)
    hb.assign_sub(d[1]*alpha)
    W.assign_sub(d[2]*alpha)
    b.assign_sub(d[3]*alpha)
  print(f'epoch: {epoch}; W: {W.numpy()}; b:{b.numpy()}; loss: {loss.numpy()}; accuracy: {accuracy}')

epoch: 0; W: [[ 0.8622582   0.31538907 -0.16085836]
 [ 1.1476147   0.77873373  0.6968705 ]
 [ 0.455634    0.11111766  0.42961314]
 [ 0.30346823  0.4367658   0.57734823]
 [ 0.8338287   0.93511087 -0.08930609]
 [ 0.66850483  0.7787399   0.58755964]
 [ 0.85921454  0.6412188  -0.02573673]
 [ 0.38217583  0.20004156  0.25088173]
 [ 0.8332083   0.05037306  0.4398839 ]
 [ 0.56785697  0.17876706 -0.09663716]]; b:1.0; loss: 211.9865264892578; accuracy: 0.3258426966292135
epoch: 1; W: [[ 0.48967835  0.45892906  0.06818144]
 [ 0.7608042   0.8931144   0.9693004 ]
 [ 0.07435989  0.25517547  0.66682947]
 [-0.0639486   0.52472466  0.85680616]
 [ 0.509298    1.1112148   0.05912068]
 [ 0.27207068  0.9022421   0.86049163]
 [ 0.51490116  0.7506518   0.20914367]
 [ 0.10401076  0.36888433  0.36020407]
 [ 0.46677405  0.13977683  0.7169145 ]
 [ 0.20308602  0.29622182  0.15067908]]; b:1.0; loss: 242.32289123535156; accuracy: 0.33146067415730335
epoch: 2; W: [[ 0.90795505  0.14254051 -0.0337067 ]
 [ 1.1691017  